/* Static launcher configuration. */
#ifndef PSTROS_STANDALONE_GAME_H
#define PSTROS_STANDALONE_GAME_H

#define STANDALONE_APP_NAME "Pstro Laucher"
#define STANDALONE_MAIN_CLASS ""
#define STANDALONE_CLASSPATH ""
#define STANDALONE_JAR_FILENAME ""
#define STANDALONE_NDS_GAME_CODE "J2DS"
#define STANDALONE_NDS_INTERNAL_TITLE "PSTROLAUNCH"
#define STANDALONE_OUTPUT_BASENAME "pstro_launcher"
#define STANDALONE_SAVE_SUBDIR ""
#define STANDALONE_SAVE_PATH "fat:/pstro_launcher.sav"
#define STANDALONE_RMS_FILTER_ENABLED 0
#define STANDALONE_RMS_STORE_1 ""
#define STANDALONE_RMS_STORE_2 ""
#define STANDALONE_PROPERTIES_TEXT ""

#endif
